name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # branch name master / main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject Environment Variables
        run: |
          sed -i 's|{{MY_SECRET_API_URL}}|${{ secrets.GOOGLE_SCRIPT_URL }}|g' script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Publishes the root directory for deployment